### ISSUE TITLE
feature: Create Player Review Page

### ISSUE THREAD

**Issue by zyzmoz** [zyzmoz/global-player#113]
# Overview

Create the page using mock data following designs [here](https://www.figma.com/file/ziqdszqhMbmj61LDNFw2E6/Supernova%3A-Global-Player?node-id=1564%3A14346) and [here](https://www.figma.com/file/ziqdszqhMbmj61LDNFw2E6/Supernova%3A-Global-Player?node-id=1564%3A14438)

# Acceptance Criteria

The page should be similar to the designs

# Out of Scope

Backend integration

**Comment by ayobamiseun** [comment]
I will like to work on this.
