### ISSUE TITLE
feature: Create Player Comparison Select Page

### ISSUE THREAD

**Issue by zyzmoz** [zyzmoz/global-player#122]
# Overview

**CSS is not a priority**

Create the page using mock data following designs [here](https://www.figma.com/file/ziqdszqhMbmj61LDNFw2E6/Supernova%3A-Global-Player?node-id=1564%3A15819)

# Acceptance Criteria

The page should be similar to the designs

# Out of Scope

Backend integration

**Comment by nirajpdn** [comment]
I want to work on this. Could you please assign this to me ?

**Comment by dlaracarvajal** [comment]
> I want to work on this. Could you please assign this to me ?

Sorry, this is a student project and only team members can work on it

**Comment by nirajpdn** [comment]
> > I want to work on this. Could you please assign this to me ?
> 
> Sorry, this is a student project and only team members can work on it

Alright, good luck.
