### ISSUE TITLE
feature: Create Auth integration

### ISSUE THREAD

**Issue by zyzmoz** [zyzmoz/global-player#21]
# Overview

Integrate the `frontend` and `backend` with some auth provider as [Auth0](https://auth0.com/docs) or [Firebase Authentication](https://firebase.google.com/docs/auth/)

# Acceptance Criteria

The user should be able to create the account and the data should be sent to our database using `/api/v1/user` endpoint

**NOTES:** Maybe we'll need to pair program this one

**Comment by probro27** [comment]
Hi @zyzmoz I can take this issue up and work with Firebase if possible
